### ISSUE TITLE
OAuth2 documentation missing in API Reference

### ISSUE THREAD

**Issue by Rayne** [f3-factory/F3com-data#86]
Original issue: https://github.com/bcosca/fatfree-core/issues/175

**Comment by Joseffb** [comment]
It's a secret shhh

Please pardon any typos as this email is sent from my iPhone

**Comment by ikkez** [comment]
That docomentation has not been written yet. Any voluntaries?

**Comment by emanwebdev** [comment]
@ikkez ok please ; just direct me pls to the "How to contribute to a good documentation" entry door.

Help, since when we click on the "Edit" button we can see on the top-right corner of each & every page of F3.com , it leads to a 404 blank page @ view-source:https://fatfreeframework.com/3.6/edit/api-reference/main

? How to start the right way please

**Comment by Rayne** [comment]
Looks like the edit button is broken.

I'm not @ikkez but here are the steps to add a new document to the API reference page:

1. Create a new document. I would choose `oauth2/main.md`
2. Add a link to the new document in the *Web Services* section at [3.6/api-reference/main.md](https://github.com/F3Community/F3com-data/blob/master/3.6/api-reference/main.md)

To test if everything is working as expected:

1. Clone https://github.com/F3Community/F3com
2. Replace the `content` directory with your `F3com-data` fork
3. Open your clone of `F3com` in the browser

**Comment by ikkez** [comment]
all fixed. should be visible when @sn0opy does the next update

workflow to add a page is:
* fork F3com and F3com-data to your account
* clone your F3Com to local maschine
* add your F3com-data fork as new remote to the submodule at `content/`
* open `http://localhost/F3com/create` URL in your browser
* save creation form, edit page, save
* commit changed files to each repo.
* push
* create pull-request

once that's done and live, the edit button on the website will lead us to the github file in edit mode.
sooo easy 😅

**Comment by richardeth** [comment]
Dit someone alreadyc reated this?
